# =====================================================================
# 全域共用變數與路徑設定 (未來修改此處，全專案 47 縣市同步更改)
# =====================================================================
global:
  input_folder: &base_input "./shinsa_tori/downloads"
  output_folder: &base_output "./shinsa_tori/outputs"

# =====================================================================
# 🎯 縣市任務設定區 (共 47 個縣市，此處以 chiba 千葉縣為例)
# =====================================================================
chiba:
  federation_name: "千葉県弓道連盟"
  extract:
    download_folder: *base_input

  transform:
    input_folder: *base_input
    output_folder: *base_output
    date_extract_type: "combined_text"
    ignore_keywords:
      - "審査日"
      - "審査会名称"
      - "級位・段位"
      - "審 査 料"
      - "登録料"
      - "連合審査"
    ffill_columns:
      - "col_0"
    shinsa_columns_map:
      col_1: "start_at"
      col_2: "name"
      col_3: "location"
    ranks_setup:
      source_column: "name"
      parse_type: "peer_to_peer"
      text_regexs:
        - '.*\((?P<ranks_text>[^)]+)\)'
    note_columns_map:
      col_4: "支部締切"
      col_5: "審査部締切"
      col_7: "雨待機場所"

fukuoka:
  federation_name: "福岡県弓道連盟"
  extract:
    download_folder: *base_input

  transform:
    input_folder: *base_input
    output_folder: *base_output
    date_extract_type: "split_columns"
    allow_keywords:
      - "地方審査"
    ignore_keywords:
      - "地方審査練習"
    ffill_columns:
      - "col_0"
    shinsa_columns_map:
      col_0: "month"
      col_1: "day"
      col_3: "name"
      col_4: "location"
    ranks_setup:
      source_column: "name"
      parse_type: "range"
      text_regexs:
        - '[\((]?(?P<ranks_text>[^()（）]*[~～〜\-][^()（）]*)[\))]'

hokkaido:
  federation_name: "札幌弓道連盟"
  extract:
    download_folder: *base_input

  transform:
    input_folder: *base_input
    output_folder: *base_output
    date_extract_type: "combined_text"
    allow_keywords:
      - "地方審査"
    ffill_columns:
      - "col_1"
      - "col_3"
    shinsa_columns_map:
      col_0: "name"
      col_1: "start_at"
      col_3: "location"
      col_4: "ranks_str"
    note_columns_map:
      ranks_str: "審査種別"
    ranks_setup:
      source_column: "ranks_str"
      parse_type: "hybrid"
      text_regexs:
        - '(?<=の)\s*(?P<ranks_text>[^\s]+)'
        - '^(?P<ranks_text>[^\s]+)(?=\s)'